services:
   registry:
      image: registry:2
      ports:
        - "5000:5000"
      environment:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data/registry
      volumes:
        - /data/registry:/data
